<<<<<<< HEAD
# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://zeleena.github.io/
baseurl: /
title: Zeleena
author: Zeleena
description: Personal blog and resume
avatar: profile.png
email: zeleenak@gmail.com
github: zeleena # username
twitter: username
linkedin: zeleena
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
=======
theme: jekyll-theme-hacker
>>>>>>> parent of 424797c... trying the sustain theme
